# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.sit_dutchdate_ext:
        class: SITBundle\Twig\DutchDate
        public: false
        tags:
            - { name: twig.extension }
    app.sit_paymentstatus_ext:
        class: SITBundle\Twig\PaymentStatus
        public: false
        tags:
            - { name: twig.extension }
    app.TwigTypeTestTwigExtension:
        class: SITBundle\Twig\TwigTypeTestTwigExtension
        public: false
        tags:
            - { name: twig.extension }
    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }
    twig.extension.decode:
        class: SITBundle\Twig\DecodeExtension
        tags:
            - { name: twig.extension }
    twig.extension.content:
        class: SITBundle\Twig\ContentExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }
    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
    app.monolog.processor.web:
        class: SITBundle\Monolog\ErrorProcessor
        arguments:
            - "@request_stack"
            - "@security.token_storage"
        tags:
            - { name: monolog.processor, method: processRecord }